### ISSUE TITLE
How to Hide it ?

### ISSUE THREAD

**Issue by AminSojoudi** [trungk18/jquery-loading#1]
I don't know how to hide indicator.

**Comment by trungvose** [comment]
Hi @AminSojoudi,

Thanks for dropping by. I will update the hide indicator and update soon since at the beginning I forgot to include it.

**Comment by AminSojoudi** [comment]
Thanks.

**Comment by trungvose** [comment]
@AminSojoudi Updated hide and destroy function. Please refer to the docs for more detail.

1. `$('#loading').loading({ hide: true});` //hide the loading indicator of its container.
2. `$('#loading').loading({ destroy: true })`; //remove the loading indicator of its container from the DOM.
